# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "ow-build" ]
  pull_request:
    branches: [ "ow-build" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all
      # matrix combinations. Consider changing this to true when your workflow
      # is stable.
      fail-fast: false

      matrix:
        build_type: [Release]
        os: [Windows, OS2, Linux]
        include:
          - image:    'windows-latest'
            dirsep:   ';'
            owimage:  '2.0'
          - image:    'ubuntu-latest'
            dirsep:   ':'
            owimage:  '2.0'
          - image:    'macos-14'
            dirsep:   ':'
            owimage:  '2.0-64'
    runs-on: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Open Watcom
      uses: open-watcom/setup-watcom@v0
      with:
        version: ${{ matrix.owimage }}
    - name: Create build subdirectory
      run: mkdir build
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only
      # required if you are using a single-configuration generator such as make.
      run: |
        cmake -B build -G "Watcom WMake" -D CMAKE_SYSTEM_NAME=${{ matrix.os }} -D CMAKE_SYSTEM_PROCESSOR=x86 -D WOLFSSL_ASM=no
    - name: Build
      run: cmake -B build -G "Watcom WMake" --config ${{ matrix.build_type }}
