name: Build Watcom C

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  wolfssl_watcomc_windows:
    if: github.repository_owner == 'wolfssl'
    strategy:
      fail-fast: false
      matrix:
        platform:
          - title:   'Windows OW 2.0'
            system:   'Windows'
            image:    'windows-latest'
            owimage:  '2.0'
          - title:   'Linux OW 2.0'
            system:   'Linux'
            image:    'ubuntu-latest'
            owimage:  '2.0'
          #- title:   'OS/2 OW 2.0'
          #  system:   'OS2'
          #  image:    'windows-latest'
          #  owimage:  '2.0'
    runs-on: ${{ matrix.platform.image }}
    name: ${{ matrix.platform.title }}
    steps:
      - name: Setup Open Watcom ${{ matrix.platform.owimage }}
        uses: open-watcom/setup-watcom@v0
        with:
          version: ${{ matrix.platform.owimage }}

      - name: Checkout wolfSSL
        uses: actions/checkout@v4
        with:
          path: wolfssl

      - name: Build wolfSSL
        working-directory: wolfssl
        shell: bash
        run: |
          cmake -B build -G "Watcom WMake" -D CMAKE_VERBOSE_MAKEFILE=TRUE -D CMAKE_SYSTEM_NAME=${{ matrix.platform.system }} -D CMAKE_SYSTEM_PROCESSOR=x86 -D WOLFSSL_ASM=no -D WOLFSSL_SINGLE_THREADED=yes -D BUILD_SHARED_LIBS=no -D WOLFSSL_EXAMPLES=no -D WOLFSSL_CRYPT_TESTS=no
          cmake --build build
